name: dental385
description: Aplicación para consultorio dental.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  font_awesome_flutter:
  google_sign_in:
  image_picker:
  qr_code_scanner:
  qr_flutter:
  table_calendar:
  url_launcher:
  # Bloc
  flutter_bloc:
  equatable:
  # Firebase
  cloud_firestore:
  firebase_auth:
  firebase_core:
  firebase_storage:
  flutterfire_ui:
  # Notifications
  awesome_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/